# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestApplyLeave():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_applyLeave(self):
    self.driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login")
    self.driver.set_window_size(1552, 832)
    self.driver.find_element(By.NAME, "username").send_keys("Admin")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("admin123")
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button").click()
    self.driver.find_element(By.LINK_TEXT, "Leave").click()
    self.driver.find_element(By.LINK_TEXT, "Apply").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bi-caret-up-fill").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".oxd-grid-item:nth-child(1) .oxd-input")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-grid-item:nth-child(1) .oxd-date-wrapper .oxd-icon").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\--offset-5 > .oxd-calendar-date").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-grid-item:nth-child(2) .oxd-date-wrapper .oxd-icon").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-calendar-date-wrapper:nth-child(5) > .oxd-calendar-date").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bi-caret-up-fill").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".oxd-grid-item:nth-child(2) .oxd-select-text-input")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-select-text--focus > .oxd-select-text-input").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".oxd-textarea")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-textarea").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-textarea").send_keys("comments")
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button").click()
    time.sleep(2)
  
